# Generated by Django 6.0.7 on 2026-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tractors/'),
        ),
        migrations.AddField(
            model_name='tractor',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tractor_videos/'),
        ),
    ]
